project:
  type: book
  output-dir: docs/

book:
  title: "Similaridade de Imagens usando Vision Transformers no python"
  reader-mode: true
  
  #navbar:
  #  search: true
  sidebar:
    logo: artigo-imagem-1.png
    title: "ViT com Python"
    text: "abc12"

  page-footer:
    left: |
      Agradecimento a <img src="facepe.png" width="30px">FACEPE pelo apoio financeiro.
    right: |
      Este material foi criado com <a href="https://quarto.org/">Quarto</a> escrito
       por <a href="https://jodavid.github.io">Jodavid Ferreira</a>.

  # cover-image: cover.jpg
  favicon: artigo-imagem-1.png
  site-url: https://jodavid.github.io/
  repo-url: https://github.com/Jodavid/similarity_vit_python/
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - dataset.qmd
    - part: tutorial.qmd
      chapters:
        - preprocess.qmd
        - similaridade.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true

    author-meta: "Jodavid Ferreira"
    include-in-header: "plausible.html"
    callout-appearance: simple

editor: source



